# Generated by Django 5.1.4 on 2025-03-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_type',
            field=models.CharField(choices=[('C-', 'Contractor'), ('I-', 'Intern'), ('E-', 'Employee')], max_length=2, null=True, verbose_name='Employee Type'),
        ),
    ]
