# Generated by Django 3.2 on 2025-06-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='old_employee_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
