# Generated by Django 5.1.4 on 2025-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_employees_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_type',
            field=models.CharField(choices=[('C-', 'Contractor'), ('I-', 'Intern'), ('E-', 'Employee')], max_length=3, null=True, verbose_name='Employee Type'),
        ),
    ]
