# Generated by Django 3.2 on 2025-06-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_employees_old_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='base_salary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
