# Generated by Django 5.1.4 on 2025-03-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_employees_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_home_city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_home_street',
            field=models.TextField(),
        ),
    ]
