# Generated by Django 5.1.4 on 2025-03-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_employees_emp_home_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_certif',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_resume',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
