# Generated by Django 5.1.4 on 2025-03-26 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_employees_emp_certif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.role'),
        ),
    ]
