# Generated by Django 3.2 on 2025-06-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_stateholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateholiday',
            name='country',
        ),
        migrations.AddField(
            model_name='stateholiday',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.state'),
        ),
    ]
