# Generated by Django 3.2 on 2025-06-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_auto_20250617_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateholiday',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.country'),
        ),
    ]
