# Generated by Django 3.2 on 2025-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_stateholiday_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='old_employee_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
