# Generated by Django 3.2 on 2025-04-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_auto_20250417_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='middle_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Middle Name'),
        ),
    ]
