# Generated by Django 3.2 on 2025-04-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_employees_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='office_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
