# Generated by Django 3.2 on 2025-06-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_alter_employees_old_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Date of Birth'),
        ),
    ]
