# Generated by Django 3.2 on 2025-04-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_employees_office_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='home_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
