# Generated by Django 3.2 on 2025-06-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_alter_employees_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_of_birth',
            field=models.TextField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
