# Generated by Django 3.2 on 2025-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_employees_home_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='home_phone',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Middle Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='office_phone',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
    ]
