# Generated by Django 3.2 on 2025-06-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_employees_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='valid_from',
            field=models.TextField(),
        ),
    ]
