# Generated by Django 3.2 on 2025-04-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_auto_20250417_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='certificates',
            field=models.FileField(blank=True, default='', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='resume',
            field=models.FileField(blank=True, default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
