# Generated by Django 3.2 on 2025-06-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_alter_employees_valid_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='total_leaves',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='used_leaves',
        ),
    ]
