# Generated by Django 3.2 on 2025-06-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_auto_20250626_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='total_leaves',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='employees',
            name='used_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
