# Generated by Django 3.2 on 2025-04-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_auto_20250421_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='incentive',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
