# Generated by Django 3.2 on 2025-06-28 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_auto_20250626_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floating_holidays_used', models.IntegerField(default=0)),
                ('casual_leaves_used', models.IntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leave_details', to='admin_app.employees')),
            ],
        ),
    ]
