# Generated by Django 3.2 on 2025-06-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_leavedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='floating_holidays_balance',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='floating_holidays_used',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='total_leaves',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='used_leaves',
        ),
    ]
