# Generated by Django 3.2 on 2025-05-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_employees_incentive'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingHolidayPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('allowed_floating_holidays', models.PositiveIntegerField(help_text='Number of floating holidays allowed this year.')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('ordinary_holidays_count', models.PositiveIntegerField(help_text='Total ordinary holidays for the year.')),
                ('min_years_experience', models.PositiveIntegerField(help_text='Minimum years of experience for extra holidays to apply.')),
                ('extra_holidays', models.PositiveIntegerField(help_text='Extra holidays allocated for experience.')),
            ],
        ),
    ]
