# Generated by Django 3.2 on 2025-06-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_auto_20250629_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='home_house',
            new_name='house_name',
        ),
    ]
