# Generated by Django 3.2 on 2025-05-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_floatingholidaypolicy_holidaypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaypolicy',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
