# Generated by Django 3.2 on 2025-06-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_rename_home_house_employees_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedetails',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
