# Generated by Django 3.2 on 2025-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_alter_holidaypolicy_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='incentive',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
