# Generated by Django 3.2 on 2025-06-30 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_leavedetails_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leave_details', to='admin_app.employees'),
        ),
    ]
