# Generated by Django 3.2 on 2025-05-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_alter_employees_incentive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emergency_contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emergency_contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emergency_contact_phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
