# Generated by Django 3.2 on 2025-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_alter_leavedetails_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedetails',
            name='total_leaves',
            field=models.IntegerField(null=True),
        ),
    ]
