# Generated by Django 3.2 on 2025-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_auto_20250512_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emergency_contact_relation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
