# Generated by Django 3.2 on 2025-07-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_leavedetails_total_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedetails',
            name='total_leaves',
            field=models.IntegerField(default=9, null=True),
        ),
    ]
