# Generated by Django 3.2 on 2025-05-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_alter_employees_emergency_contact_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
