# Generated by Django 3.2 on 2025-07-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_alter_leavedetails_total_leaves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavedetails',
            old_name='total_leaves',
            new_name='total_casual_leaves',
        ),
    ]
