# Generated by Django 3.2 on 2025-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_alter_employees_emergency_contact_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
