# Generated by Django 3.2 on 2025-05-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_auto_20250513_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
