# Generated by Django 3.2 on 2025-07-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_alter_leavedetails_total_casual_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavedetails',
            name='pending_casual',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leavedetails',
            name='pending_float',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leavedetails',
            name='planned_casual',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='leavedetails',
            name='planned_float',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
