# Generated by Django 3.2 on 2025-05-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0024_leaverequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatingholiday',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_app.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_app.country'),
            preserve_default=False,
        ),
    ]
