# Generated by Django 3.2 on 2025-05-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_auto_20250519_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatingholidaypolicy',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_app.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holidaypolicy',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_app.country'),
            preserve_default=False,
        ),
    ]
