# Generated by Django 3.2 on 2025-07-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_employees_hr_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='hr_emails',
        ),
    ]
