# Generated by Django 3.2 on 2025-07-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_remove_employees_hr_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='hr_emails',
            field=models.BooleanField(default=False),
        ),
    ]
