# Generated by Django 3.2 on 2025-05-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_holidayresetperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floatingholidaypolicy',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
