# Generated by Django 3.2 on 2025-07-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_auto_20250721_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankDetails',
            new_name='SetUpTable',
        ),
    ]
