# Generated by Django 3.2 on 2025-08-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_rename_bankdetails_setuptable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='role'
        ),
        migrations.AlterModelTable(
            name='country',
            table='country'
        ),
        migrations.AlterModelTable(
            name='state',
            table='state'
        ),
        migrations.AlterModelTable(
            name='salutation',
            table='salutation'
        ),
        migrations.AlterModelTable(
            name='department',
            table='department'
        ),
        migrations.AlterModelTable(
            name='employeetype',
            table='employeetype'
        ),
        migrations.AlterModelTable(
            name='employees',
            table='employees'
        ),
        migrations.AlterModelTable(
            name='leavedetails',
            table='leavedetails'
        ),
        migrations.AlterModelTable(
            name='communication',
            table='communication'
        ),
        migrations.AlterModelTable(
            name='setuptable',
            table='setuptable'
        ),
        migrations.AlterModelTable(
            name='resume',
            table='resume'
        ),
        migrations.AlterModelTable(
            name='certificate',
            table='certificate'
        ),
        migrations.AlterModelTable(
            name='holiday',
            table='holiday'
        ),
        migrations.AlterModelTable(
            name='stateholiday',
            table='stateholiday'
        ),
        migrations.AlterModelTable(
            name='leaverequest',
            table='leaverequest'
        ),
        migrations.AlterModelTable(
            name='floatingholiday',
            table='floatingholiday'
        ),
        migrations.AlterModelTable(
            name='holidaypolicy',
            table='holidaypolicy'
        ),
        migrations.AlterModelTable(
            name='floatingholidaypolicy',
            table='floatingholidaypolicy'
        ),
        migrations.AlterModelTable(
            name='holidayresetperiod',
            table='holidayresetperiod'
        ),
    ]
