# Generated by Django 3.2 on 2025-08-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0031_auto_20250801_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='password',
        ),
    ]
