# Generated by Django 3.2 on 2025-05-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0031_auto_20250521_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='designation',
        ),
    ]
