# Generated by Django 3.2 on 2025-08-19 12:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_remove_employees_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='AssignProject',
            fields=[
                ('emp_prj_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='admin_app.employees')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, help_text='Role of the employee in this project', max_length=100, null=True, verbose_name='Designation in Project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                
            ],
            options={
                'verbose_name': 'Assigned Project',
                'verbose_name_plural': 'Assigned Projects',
                'db_table': 'assignproject',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_alias', models.CharField(max_length=20, unique=True)),
                ('client_addr', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='admin_app.country')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('costcenter_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('costcenter_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'costcenter',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='admin_app.client')),
                ('project_name', models.CharField(max_length=255)),
                ('project_desc', models.TextField(blank=True, help_text='A brief description of the project.', null=True, verbose_name='Project Description (Short)')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prj_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='admin_app.employees', verbose_name='Project Manager')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetHdr',
            fields=[
                ('tsheet_id', models.AutoField(primary_key=True, serialize=False)),
                 ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_headers', to='admin_app.employees')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('tot_hrs_wrk', models.IntegerField(default=0)),
                ('tot_hol_hrs', models.IntegerField(default=0)),
                ('tot_lev_hrs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delayed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to='admin_app.employees')),        
            ],
            options={
                'db_table': 'timesheet_hdr',
            },
        ),
        migrations.CreateModel(
            name='WrkLocation',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'wrklocation',
            },
        ),
        migrations.CreateModel(
            name='TimesheetItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_items', to='admin_app.timesheethdr')),
                ('project', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.project')),
                  ('costcenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.costcenter')),
                ('wrk_date', models.DateField()),
                ('wrk_hours', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='admin_app.activity')),
                 ('work_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='admin_app.wrklocation')),
                ('project_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_items', to='admin_app.assignproject')),
               
            ],
            options={
                'db_table': 'timesheetitem',
            },
        ),
        migrations.AddField(
            model_name='assignproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='admin_app.project'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='project_is_acti_ce764b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client'], name='project_client__3ae9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['valid_to'], name='project_valid_t_6fc34a_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(valid_from__lte=django.db.models.expressions.F('valid_to')), name='valid_date_range_check'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('project_name', 'client'), name='unique_project_per_client'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_alias'], name='client_client__efc8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_deleted'], name='client_is_dele_84d073_idx'),
        ),
        migrations.AddIndex(
            model_name='assignproject',
            index=models.Index(fields=['employee', 'project'], name='assignproje_employe_7d31f5_idx'),
        ),
        migrations.AddIndex(
            model_name='assignproject',
            index=models.Index(fields=['start_date'], name='assignproje_start_d_0c68a7_idx'),
        ),
        migrations.AddIndex(
            model_name='assignproject',
            index=models.Index(fields=['end_date'], name='assignproje_end_dat_4df43e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignproject',
            unique_together={('employee', 'project', 'start_date')},
        ),
    ]
