# Generated by Django 3.2 on 2025-05-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0032_remove_employees_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('resigned', 'Resigned')], default='employed', max_length=10),
        ),
        migrations.AlterField(
            model_name='employees',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
