# Generated by Django 3.2 on 2025-08-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0033_auto_20250819_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='working_hours',
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='employees',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='admin_app.costcenter'),
        ),
    ]
