# Generated by Django 3.2 on 2025-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0033_auto_20250521_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('resigned', 'Resigned'), ('Inern to employee', 'Inern to employee')], default='employed', max_length=50),
        ),
    ]
