# Generated by Django 3.2 on 2025-08-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_auto_20250819_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to='admin_app.employees'),
        ),
        migrations.AddField(
            model_name='assignproject',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_updated', to='admin_app.employees'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to='admin_app.employees'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_updated', to='admin_app.employees'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to='admin_app.employees'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_updated', to='admin_app.employees'),
        ),
        migrations.AlterField(
            model_name='assignproject',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation in Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Project Description'),
        ),
    ]
