# Generated by Django 3.2 on 2025-05-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0035_auto_20250521_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('resigned', 'Resigned'), ('Intern to employee', 'Intern to employee')], default='employed', max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='home_house',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='home_post_office',
            field=models.TextField(null=True),
        ),
    ]
