# Generated by Django 3.2 on 2025-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0037_auto_20250822_1133'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_is_dele_84d073_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='client_is_acti_9a8432_idx'),
        ),
    ]
