# Generated by Django 3.2 on 2025-05-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0038_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Aadhaar Number'),
        ),
        migrations.AddField(
            model_name='employees',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='employees',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Branch'),
        ),
        migrations.AddField(
            model_name='employees',
            name='bank_branch_address',
            field=models.TextField(blank=True, null=True, verbose_name='Bank Branch Address'),
        ),
        migrations.AddField(
            model_name='employees',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='employees',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='employees',
            name='pan_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Card Number'),
        ),
    ]
