# Generated by Django 3.2 on 2025-09-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0039_auto_20250825_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='excl_folup',
            field=models.BooleanField(default=False),
        ),
    ]
