# Generated by Django 3.2 on 2025-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0039_auto_20250525_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='pm_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='PM Email'),
        ),
    ]
