# Generated by Django 3.2 on 2025-09-22 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0040_employees_excl_folup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lmodel', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'device_brand',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lmodel', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(db_column='brand', on_delete=django.db.models.deletion.CASCADE, to='admin_app.devicebrand')),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('proc_date', models.DateField()),
                ('retire_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'device_type',
            },
        ),
        migrations.CreateModel(
            name='DeviceTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_trackers', to='admin_app.employees')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_trackers', to='admin_app.devices')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),               
            ],
            options={
                'db_table': 'device_tracker',
            },
        ),
        migrations.AddField(
            model_name='devices',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, to='admin_app.devicetype'),
        ),
        migrations.AddConstraint(
            model_name='devicetracker',
            constraint=models.UniqueConstraint(condition=models.Q(end_date__isnull=True), fields=('device',), name='unique_active_device_assignment'),
        ),
    ]
