# Generated by Django 3.2 on 2025-09-23 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0041_auto_20250922_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicebrand',
            old_name='lmodel',
            new_name='device_model',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='brand',
            new_name='device_brand',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='lmodel',
            new_name='device_model',
        ),
        migrations.RenameField(
            model_name='devices',
            old_name='type',
            new_name='device_type',
        ),
        migrations.RenameField(
            model_name='devicetype',
            old_name='type',
            new_name='device_type',
        ),
    ]
