# Generated by Django 3.2 on 2025-09-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0042_auto_20250923_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicebrand',
            old_name='device_model',
            new_name='device_brand',
        ),
    ]
