# Generated by Django 3.2 on 2025-09-24 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0043_rename_device_model_devicebrand_device_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.devicebrand'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.devicetype'),
        ),
    ]
