# Generated by Django 3.2 on 2025-09-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0046_auto_20250924_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
