# Generated by Django 3.2 on 2025-09-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0047_devices_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('symbol', models.CharField(max_length=5, verbose_name='currency symbol')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currency',
            },
        ),
    ]
