# Generated by Django 3.2 on 2025-09-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0048_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='currency',
            field=models.ForeignKey(blank=True, default='INR', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='admin_app.currency'),
        ),
    ]
