# Generated by Django 3.2 on 2025-12-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0049_devices_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheethdr',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
