# Generated by Django 3.2 on 2026-03-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0050_alter_timesheethdr_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='excl_TSheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='floatingholiday',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='stateholiday',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
