"""
Django settings for hrms_project project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


#google recaptcha
RECAPTCHA_PUBLIC_KEY = '6Leh9VYrAAAAAHx03L847AT7KPXQKmhEHL3RYzzF'
RECAPTCHA_PRIVATE_KEY = '6Leh9VYrAAAAABJiXJD7AH6db5-ksN-mE7Pdfgdc'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0^uf$ncl^q&^-^%$gquf!84c&v%=%a1&j94pww++7g6dwd0z0('
#
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ["35.225.224.226", "127.0.0.1"]
ALLOWED_HOSTS = ["34.58.114.68","127.0.0.1",'localhost','*','34.29.104.90','employee.spectrasoln.com']

#added for domain
CSRF_TRUSTED_ORIGINS = [
    'https://employee.spectrasoln.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'django_cron',
    'employee_app',
    'admin_app'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'hrms_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'admin_app','templates'),os.path.join(BASE_DIR, 'employee_app','templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hrms_project.wsgi.application'

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage" 


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # or 'django.db.backends.mysql' for MySQL
        'NAME': os.getenv('HRMS_DB_NAME'),
        'USER': os.getenv('HRMS_USER'),
        'PASSWORD': os.getenv('HRMS_PASSWORD'),
        'HOST': os.getenv('HRMS_HOST'),  # or 'localhost' if using Cloud SQL Proxy
        'PORT': '5432',  # PostgreSQL default port, or '3306' for MySQL

    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


#
# STATIC_URL = 'static/'

# Add the following to make Django aware of your static files directory

# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# BASE_DIR / "employee_app/static",  # Path to employee app's static directory
#
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# media configuration

import os

# # MEDIA_URL and MEDIA_ROOT settings
# MEDIA_URL = '/media/'  # URL prefix for serving media files
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Folder where media files are stored
#





#setting.py
AUTHENTICATION_BACKENDS = [
    'employee_app.backends.EmailBackend',  # Add your custom backend here
    'django.contrib.auth.backends.ModelBackend',  # Default backend (you can keep it as fallback)
]

DEFAULT_FROM_EMAIL='lms@spectrasoln.com'


# settings.py
import os

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.spectrasoln.com'  # Updated from 'smtp.spectrasoln.com'
EMAIL_PORT = 465  # Updated to use the SSL port as specified
EMAIL_USE_SSL = True  # Use SSL for secure email sending
EMAIL_HOST_USER = 'lms@spectrasoln.com'
EMAIL_HOST_PASSWORD = 'LMS@SpEctra'  # Make sure the password is set in your environment





import os
from pathlib import Path

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent




import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Retrieve admin credentials
ADMIN_USERNAME = os.getenv('ADMIN_USERNAME')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL')
ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD')


CRON_CLASSES = [
    'admin_app.cron.BirthdayEmailCronJob',
]

DJANGO_CRON_DELETE_LOGS_OLDER_THAN = 4


CELERY_BROKER_URL = 'redis://default:R3e2Ldfwug7kz20OsBx6SCo32ifBdO88@redis-14395.crce179.ap-south-1-1.ec2.redns.redis-cloud.com:14395'
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'